version: '3'
services:
  node-app:
    container_name: exp-node-app
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    command: npm run start-dev